language: ruby
cache: bundler

rvm:
- 2.4.1

before_script:
  - chmod +x ./scripts/cibuild # or do this locally and commit

# Assume bundler is being used, therefore
# the `install` step will run `bundle install` by default.
script: ./scripts/cibuild

# branch whitelist, only for GitHub Pages
branches:
  only:
  - master    # test the master branch only

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
  secure: "kGQSjcy77/oDWlLHGBDf7cSARmfqXjZ955c8E3wIfAflJr+7+f/OHrbc/4WB5ji9YacFxIZLgYuQiWqe34cg8y6DaBoi1FEZOqk9VYWnT+JHZ35xQKvNVwrd4mg6TrCYasA3TWIiYpMAbiYoTfpeblBWAkLx5Zj4DhBnGcykEzfe/H3pR+EpHDccHjkx0dENzqIkb3DIKIdHhQ1jpGT5gN1F92d+4pyxVjK0oHffahGBMTiIlmFyA12yCrEuNfFPtGdB9TbK5A2HPMxieRH4KGrT9fHdtagtlEkoJbbosVzfpxeKi3D13HNuPsprVs4O4X9UJ86wtOuAKGWVZWXwFDo+H+f/2pVuqzMNnGAjbIDTQp/YbwwfHZLQBmCkBzMxmgBsmP/V3kP0nIJ7I8VmUlO4SBREggIynG71QVeGCsOo189P0a99cIoiF42LbCsYi9j5LGC4Z1Hpjt3Q1xKrSlbviX5ABcClHzcDuqQq0fq+pd9wi0k4hs2iChSQwt3Wa8/suNzUeOGahbUQAiGtczB3t+lO0ESabrHc23rjo6qkkMyBHZ7fXdDGQ+eN+/sRh/WiarBsYb2vNWDNpqDZ3X73jNxUMYSKXtyJ4gztZS0RKFDHdmCclmJvUtoFTiPFqcgVIzFCOPSNuJe7Exa2le0DppiTd4ed3y04unb20sk="

sudo: false # route your build to the container-based infrastructure for a faster build
