# Site settings
title: MC notes
description: Open Data Science built upon Jupyter Notebooks
url: "http://mcnotes.github.io" # the base hostname & protocol for your site


# github
username: trallard
repo:     MCNotes
branch:   master


# Build settings
markdown: kramdown
include: ['_pages']
highlighter: rouge
exclude:
  - .gitignore
  - README.md
  - jekyll.py
  - jekyll.tpl
  - replace.py
  - Gemfile*
  - vendor
  - travis.yml
  - vendor

# to ensure the links work properly
permalink: pretty

# Additional gems
gems:
  - jekyll-seo-tag
  - jekyll-sitemap

# SASS directory
sass:
  style: compressed
  sass_dir: _sass

# jekyll source/destination
source: .
destination: _site
