# Site settings
title: MC notes
description: Open Data Science built upon Jupyter Notebooks
url: "http://ms-notes.github.io" # the base hostname & protocol for your site


# About
author:
  name: Tania Allard


# Build settings
markdown: kramdown
include: ['_pages']
highlighter: rouge
exclude:
  - .gitignore
  - README.md
  - jekyll.py
  - jekyll.tpl
  - replace.py

# to ensure the links work properly
permalink: pretty

# Additional gems
gems:
  - jekyll-seo-tag
  - jekyll-sitemap

# SASS directory
sass:
  style: compressed
  sass_dir: _sass
